//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yonetim.UI.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depo()
        {
            this.Uruns = new HashSet<Urun>();
        }
    
        public int DepoId { get; set; }
        public string Ad { get; set; }
        public string Tanim { get; set; }
        public int KisiId { get; set; }
        public Nullable<int> UrunId { get; set; }
    
        public virtual Kisi Kisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun> Uruns { get; set; }
    }
}
